### ISSUE TITLE
Adding a new annotation or label is supported?

### ISSUE THREAD

**Issue by nak3** [knative/operator#165]
**Problem**

- This is a kind of question but opened this ticket to confirm it for sure.
- When adding a new label or annotation to a deployment or template.metadata.annotation, it is not reconciled by operator.
- For example, following labels or annotations are NOT reconciled.

e.g 1
```
kubectl label deployments.apps -n knative-serving activator newlabel=foo
```
e.g 2
```
kubectl patch deployments.apps -n knative-serving activator -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true"}}}}}'
```

So, is it alright to add new labels or annotations by users' command? My concern is that it is a bug actually and will not be available in the future.

**Comment by jcrossley3** [comment]
I believe the behavior depends on _how_ the user adds the annotation or label. The operator will apply a three-way merge using the value of the `kubectl.kubernetes.io/last-applied-configuration` annotation. So if a user adds the annotation/label using `kubectl apply` that will of course include those in `kubectl.kubernetes.io/last-applied-configuration`. And because they're there and not in the operator's manifest, the operator will delete them. As long as they're not present in `kubectl.kubernetes.io/last-applied-configuration` the operator should leave them alone.

Make sense?

**Comment by jcrossley3** [comment]
The operator should behave exactly as if some other user is invoking `kubectl apply` on the resource you're attempting to label/annotate. That behavior is described here: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#merge-patch-calculation

**Comment by nak3** [comment]
Thank you @jcrossley3 Yes, that makes sense.

But so, in a nutshell, it is safe to add annotation by `kubectl patch deployments.apps -n knative-serving activator -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true"}}}}}'`?

What I am worried is that the annotation might be removed during upgrade or some events. If it is not 100% sure, I would like operator to support some other way which is guaranteed.

**Comment by jcrossley3** [comment]
The annotation should remain as long as the deployment exists, and it should remain even when other fields are changed -- even other annotations -- because the operator should leave it alone if it's not mentioned in its internal manifest.

Of course, if it's ever deleted and re-recreated, the annotation won't survive that, obviously.

And if `kubectl apply ...` is used, that won't work either.

If it's something you want to persist across those possible events, then yes, I would suggest you bring that annotation under the operator's control via either a new CR field or a `Transformer` in the operator itself.

**Comment by jcrossley3** [comment]
BTW, if this annotation is related to istio, it could be handled as a part of our new ingress API: #92

**Comment by nak3** [comment]
Thank you so much @jcrossley3 It is super clear now. I am closing this.
