### ISSUE TITLE
Change the bahavior when spec.version is not set

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#215]
If spec.version is not set, we now pick the latest available version under kodata for knative.

I am rethinking if we should change it:
1. when spec.version is not set and there is no knative installed, pick up the latest.
2. when spec.version is not set and there is Knative install, stay with the existing version.

We need to give users staying with older versions a chance, to incrementally bump up their knative versions.

For example, users have 0.14.2 eventing installed, when we install 0.16.0 operator, the operator tires to install 0.1.6.x directly, operator fails.

If we can still use 0.14.2, when installing 0.1.6.0 operator. Users can still have operator with raising errors, and upgrade to 0.15.x and then 0.16.x with 0.16.0 operator.

**Comment by jcrossley3** [comment]
This is a pretty significant change. Currently, we have downstream users who expect to upgrade their knative install by simply upgrading their knative operator. If I understand you correctly, you're suggesting we should instead expect them to not only upgrade their operator but also edit their knative CR, correct? Why?

**Comment by Cynocracy** [comment]
We could consider using a sentinel version, maybe something self-descriptive like 'adopt-oncluster'

**Comment by evankanderson** [comment]
I'm not convinced that this is necessary or expected behavior.

If upgrading from 0.15 to 0.16, `spec.version` will be unset. In previous versions of the operator, upgrading the operator would _implicitly_ upgrade the version of serving. While that's no longer a requirement, it seems reasonable to preserve that behavior.

For non-operator-managed installs, it similarly seems reasonable to consider the installation of the operator **and creation of the resource** to be a signal that the cluster administrator would like to install the version of Knative associated with the operator which was installed. If the cluster administrator wants to keep the same version, they can specify `spec.version` when creating the custom resource.

**Comment by houshengbo** [comment]
@evankanderson @jcrossley3 From 0.15.x to 0.16.x, only going up one minor version, the upgrade works fine.
However, when you try install 0.16.x on top pf an existing 0.14.2 with CR created, you will end up with warning message "version not supported to upgrade..." constantly popping up in the log. The CR status shows `error` too. Knative service still function. I just do not feel comfortable with this bahavior.

**Comment by jcrossley3** [comment]
> @evankanderson @jcrossley3 @Cynocracy From 0.15.x to 0.16.x, only going up one minor version, the upgrade works fine.
> However, when you try install 0.16.x on top of an existing 0.14.2 with CR created, you will end up with warning message "version not supported to upgrade..." constantly popping up in the log. The CR status shows `error` too. Knative service still function. I just do not feel comfortable with this behavior.

So, to be clear, your use case is not just that `spec.version` isn't set. It's that `spec.version` isn't set *AND* `status.version` is more than one minor release behind the latest provided by the operator. I think the solution depends on the result of this: https://github.com/knative/serving/issues/8629

**Comment by Cynocracy** [comment]
I'm convinced that the spec unset case *where the Operator was already
managing installation* should stick to latest.
If that translates into 'when status is set, always use latest' I'm happy
with that behavior :)
