### ISSUE TITLE
Good idea to separate CR and knative components into different namespaces?

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#219]
We now install operator CR and knative under the same namespace.

I was asked by the production team in my company, whether they can be put under different namespaces.

The benefit is that when the ns of knative is removed by accident, the CR can still revive it.

**Comment by jcrossley3** [comment]
Very early incarnations of the operator did exactly this. Ultimately, it led to confusion since cross-namespace owner-refs aren't allowed, so we couldn't rely on garbage-collection to delete the namespace-scoped resources. Strangely, we also received complaints from users that they couldn't find the CR associated with their deployed knative component[s]. We eventually decided the `spec.namespace` field wasn't worth the trouble and removed it.

Besides, what's preventing the ns of the CR from being removed by accident? ;)

**Comment by kramvan1** [comment]
In our case we are managing the operator CR's in a different namespace for to allow complete separation from any namespace(s) the operator has to maintain.   The CR itself and it's namespace are reconciled independently to allow recovery from any deletions or changes.   Our users don't need to care about the CR or where it's located, it's all managed/controlled for them.

The operator control plane namespace could also be deleted and the operator/cr should be able to recovery from that scenario with another reconcile loop.
We are trying to keep a separate of control here to allow for maximum recovery coverage.

I understand the garbage collection issue, and I have seen the owner refs placed in labels and be handled by the operator upon deletion of the CR.

**Comment by evankanderson** [comment]
How would the operator + CR recover from the control plane namespace being deleted? Once that namespace is deleted, none of the operator processes would be running.

**Comment by kramvan1** [comment]
Operator and CR are in separate ns from the control plane, this allow them to be managed and controlled independently of the control plane.
