### ISSUE TITLE
Update HA logic

### ISSUE THREAD

**Issue by nak3** [knative/operator#337]
**Describe the bug**

- As per current HA logic code in https://github.com/knative/operator/blob/18aca414e5109ee3f66b4431430616c65ef799ab/pkg/reconciler/knativeserving/common/ha.go 
it still checks `enabledComponents` in configmap. The parameter was removed by https://github.com/knative/serving/commit/584d41b1723f3a7aa7ab4181638793f47cb2a430.
- Also, the HA serving's components are basically "controller" "webhook" "autoscaler-hpa" "autoscaler" "domainmapping-webhook" but all of them are not covered.

**To Reproduce**

- One of the problem is that `high-availability.replicas` in KnativeServing does not scale up autoscaler.

**Comment by houshengbo** [comment]
@nak3 Initially, the HA in operator only supported the leader-selected deployments:
https://knative.dev/docs/install/operator/configuring-serving-cr/#high-availability. It was just controller, autoscaler-hpa, and networking-istio.

Per enabledComponents, I think we probably need to keep it for a while, because operator maintain minor version minus 3. Old version of knative serving could still have it?

**Comment by nak3** [comment]
Yeah, the operator maintain minor version minus 3, then `enabledComponents` should be remained.

For HA components, ingress plugins also needs to be considered once https://github.com/knative/operator/pull/312 was merged.
