### ISSUE TITLE
Knative-ingress-gateway changes are overwritten by operator

### ISSUE THREAD

**Issue by jheyduk** [knative/operator#505]
**Describe the bug**
I changed my configuration as described on https://knative.dev/docs/serving/using-a-tls-cert/
On next reconcile my changes are lost.

**Expected behavior**
The operator should not overwrite the settings.
Otherwise the documentation should extended how to make the changes persist using KnativeServing CRD

**To Reproduce**
Make some changes on Knative-ingress-gateway and wait for the next reconcile. The added `-hosts`-Section will disappear

**Knative release version**
v0.21

**Comment by houshengbo** [comment]
If you install knative serving with the operator, configure it with the operator. 

In terms of Knative-ingress-gateway, you should configure it as the instructions here: https://knative.dev/docs/install/operator/configuring-serving-cr/#configuration-of-knative-ingress-gateway

If you want to change the default content of `knative-ingress-gateway`, operator reconciling loop will revert it, because it loads the default `knative-ingress-gateway` each time and apply in the loop.

**Comment by houshengbo** [comment]
It also reminds me something similar in the old archive:
https://github.com/knative/serving-operator/pull/258
https://github.com/knative/serving-operator/issues/302

Time to revive.
