### ISSUE TITLE
Adopt controller-runtime 

### ISSUE THREAD

**Issue by MartinForReal** [knative/operator#521]
**Problem**

Follow controller development best practice and Adopt kubebuilder, controller-runtime and etc.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
Contributors

**Exit Criteria**

All functions are working as expected

**Time Estimate (optional):**
7 days
**Additional context (optional)**

https://github.com/kubernetes-sigs/controller-runtime/

**Comment by MartinForReal** [comment]
please move to knative/pkg if it is feasible

**Comment by houshengbo** [comment]
@MartinForReal To keep consistent with all knative projects, we leverage the structure the same as any other knative project.
The community had this discussion 2 years ago, when operation wg was founded.

The knative common package, knative/pkg, has already established a mature backbone for other knative projects to rely on.

controller-runtime is just one lib to produce kube operator, but it is NOT the only one.

**Comment by houshengbo** [comment]
Don't make a beauty contest between controller-runtime and knative/pkg. It is NOT which one beats one another.
They are both great libs. To determine which one to use, it is all based on the time and nature of the project.
For newly created projects, there could be decisions made towards either direction, but for projects, which have been developing for a while, and have already developed the ecosystem in a certain degree, it may be past due to make these decisions, since we departed a long time ago. At the beginning of knative, neither kubebuilder or operator-sdk, based on controller-runtime, was mature enough, to demonstrate the prosperity, so knative made the decision to move on with its own implementation.

By far, **in my personal opinion**, knative/pkg has got the controller and reconciler wrapped up NOT bad. And in terms of webhooks, I love knative/pkg more, coz it surely takes less effort to add any type of webhook. Last but not least, I am a fan of the tool `knative.dev/pkg/apiextensions/storageversion` to migrate older version of resources into new version, once the CRDs bump into new version. controller-runtime does not have it by far.

What is good about controller-runtime is that you can either leverage operator-sdk or kubebuilder as the command tool to scaffold, build and publish everything. However, the drawback is that you have keep you golang cod, annotations, tags, manifests, etc, everything in-sync and the project structure has been FORCED to write in a RIGID way.
You have to obey the rules that changing the source code and annotations, and run the commands to generate the rest. You can not tolerate anything NOT in-sync. Once it happened, after running the command to regenerate the manifests, you never know what will overwrite what.

knative/pkg lacks a systematic tool as the command line to generate everything, but on the other hand, it offers some certain degree of flexibility for developers to maintain the project code.

This comment is more of my own opinion and experience, working with both of the libs. 

Another example you can refer to is the tekton operator. At the beginning, I was the only one, who insisted to leverage knative/pkg as the lib to write the operator, but all the others went with controller-runtime. However, one year later, they found out that all existing Tekton tools and processes were built based on knative/pkg, if operator did not, they cannot leverage any existing building process, so they decided to change the framework from controller-runtime into knative/pkg, to make tekton operator a real citizen of tekton community: https://github.com/tektoncd/operator.

It is not a beauty contest, it is just what works for the project and the community.

**Comment by MartinForReal** [comment]
Fair enough , Thanks for the clarification! :)
