### ISSUE TITLE
It is better to drop spec.version?

### ISSUE THREAD

**Issue by nak3** [knative/operator#570]
As the original PR also asked the feedback https://github.com/knative/operator/pull/207#issuecomment-661422069, I would like to give the feedback.
Actually I am thinking that it is better to drop `spec.version` configurations with two big reasons:

#### 1. What is the usecase for spec.version?
- I'm curious if there is any reason that some users need to deploy v0.21 operator but want to use old v0.20 serving/eventing.
- The operator does not support future version (e.g. v0.20 operator does not support to deploy v0.21 or nightly serving/eventing) so the spec.version cannot be used for testing purpose.

#### 2. The code became complicated
- For example, it causes an issue like https://github.com/knative/operator/issues/556. I think it could not be fixed quickly as code is complicated.
- Also as operator maintains 3 minus versions so the issue like https://github.com/knative/operator/issues/337 cannot be solved quickly.
- Finally the rule of "how to add manifest in `cmd/operator/kodata/knative-serving/`" is very complicated. Operator checks version directory, version label in the manifest file and so on.

**Comment by houshengbo** [comment]
@nak3 
We used to have a long discussion on this topic almost two years, when we start to think about making upgrade smooth and fallback possible. What I can remember as the reasons to support the version includes, but not limited to:

In general, it provides a more convenient path to upgrade and fallback. 

1. As we only makes sure upgrade or downgrade to the adjacent minor version, if the operator does not support multiple versions of knative, we have install multiple versions of the operator one-by-one, in order to catch up to the latest version.

With the `spec.version` plus minus 3 versions, we give the users a buffer to install the newest version of operator, and upgrade from an old version to the newest, without installing operator multiple times. (converting from going up one version into going up three versions, with one operator version).

2. Help to fall back: If the upgrade fails, it would be very difficult to maintain, if we do not support multiple versions. What would the user do in that case? Install the old version of operator back? The problem is downgrade is surely not just a reverse of upgrade, the future version can know what is in the older version does not know what is in the future. 
Having one version of operator supporting multiple versions of knative is to create the buffer for the operator to know both the past and the future. If the upgrade fails, there is no need to install old operator, just specify spec.version to the old version, then the downgrade should be OK.

  a One version of knative operator support

**Comment by nak3** [comment]
Thank you for the explanation.
Both points could also be addressed by using `KO_DATA_PATH`, correct?
Actually our downstream's CI is testing the latest version by using a configmap with pointing the path by `KO_DATA_PATH`.
`KO_DATA_PATH` has some advantages:
- It can test the latest version - i.e. v0.22 manifest can be tested by v0.21 operator without operator upgrade.
- It can also test the previous versions.
- The rollback is also very simple - just remove the `KO_DATA_PATH` value.

So, I think operator can still provide the convenient path to upgrade and fallback without `spec.version`.

> if we do not support multiple versions. What would the user do in that case? Install the old version of operator back?

No, as I mentioned above, we can create a configmap and point the manifest path by `KO_DATA_PATH`. Installation of old operator is not necessary.

**Comment by houshengbo** [comment]
@nak3 I do no think you can do it by only changing KO_DATA_PATH. You have to mount the volume with the correct manifests.
 
The CI does not use any configmap, it only builds an new image with the expected manifests under kodata.

For example, you have installed 0.19 operator, you want to install 0.22 operator to upgrade to the newest knative.
How are you gonna change the KO_DATA_PATH? First, change to install 0.20, then change it to install 0.21, and change it to install 0.22?

In that case, I still prefer to have spec.version, because applying the CR one time is more convenient, and takes less effort than changing KO_DATA_PATH and mounting new manifests.

**Comment by houshengbo** [comment]
In addition, without spec.version, if you install a certain version of knative serving, how to find the mapping ingress with the correct version?(Like human operators remembering the version, finding the correct ingress version, putting them into kodata? If users want to upgrade, go to find the correct the version of knative, and map the correct version of ingress & re-create the manifests under kodata)

**Comment by houshengbo** [comment]
Speaking of ConfigMaps, I know it has not reached there yet, but the WG has been trying hard to slow down the pace with configurations by ConfigMaps, and promoting configurations with CRs as much as possible.

**Comment by nak3** [comment]
I mentioned about `KO_DATA_PATH` just for a temporary workaround, like to fall back when upgrade failed or to skip a version. I didn't expect that it continues to be used.
For example, v0.19 to v0.21 upgrade (skip v0.20), KO_DATA_PATH is temporary used for v0.20 only once in the short period.
So, users should expect 0.22 operator install 0.22 serving/eventing. And they do not need to look for the correct ingress version but use ingress manifests bundled in operator.

Also, I assumed that KO_DATA_PATH is used by configmap created by `kubectl create configmap ko-data-serving --from-file=0.21.0/1-serving-crds.yaml ...`. (And of course, operator pod needs to mount the configmap...)
So if someone wants to skip two versions, then update the configmap (e.g. `kubectl create configmap ko-data-serving --from-file=0.22.0/1-serving-crds.yaml --dry-run=client -o yaml | kubectl replace  -f -`). It only changes the contents in configmap, not much effort.

**Comment by houshengbo** [comment]
```
And of course, operator pod needs to mount the configmap
```
I prefer not do that. I would rather keep the configurations with the CRs.

**Comment by nak3** [comment]
Hmmmm.... So in conclusion:
- operator supports `spec.version` for some unusual cases like to fall back or to skip minor versions during upgrade. (Please let me know if it covers other cases.)
- KO_DATA_PATCH can also cover such cases, but operator wg wants to keep `spec.version` as configuration should be in CR, which is simpler.

Honestly I still wonder if it is worth to support it by devoting maintainability(e.g. https://github.com/knative/operator/issues/337) and quality(e.g. https://github.com/knative/operator/issues/556#issuecomment-828047443) :sweat_smile:
But I think I should follow the wg decision so maybe `spec.version` should be kept.

Anyway thank you for the explanations!
